/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:89d21ab6-752c-4d74-96cd-491d5ba50d02",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_4WflHc8Ea",
    "aws_user_pools_web_client_id": "4mlnoj9nj6707c2mffsej3kojq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "timestreamaccessapi",
            "endpoint": "https://fxxok2wf3d.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ],
    "aws_user_files_s3_bucket": "s3sensordatabucket41ff7-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
